### ISSUE TITLE
看错了

### ISSUE THREAD

**Issue by zhongfly** [flaribbit/bilibili-manga-spider#1]
看错了

**Comment by flaribbit** [comment]
哈，感谢捧场~

**Comment by zhongfly** [comment]
我之前使用app的接口，index的接口是https://manga.bilibili.com/twirp/comic.v1.Comic/Index，最近改成https://manga.bilibili.com/twirp/comic.v1.Comic/GetImageIndex了，我还以为加密改了

**Comment by flaribbit** [comment]
好的 谢提醒【另外 原来有人写过index解密算法了啊。。我当时没搜到然后硬啃的js 哭了

**Comment by zhongfly** [comment]
我当时也找了很久，最后才找到一个…主要是不会js，啃不动。现在搜了下，写B站漫画的已经不少了～原来有打算写一下积分换全场券的，现在都懒得写了

flaribbit <notifications@github.com> 于 2019年11月6日周三 20:58写道：
